### ISSUE TITLE
basic usage example

### ISSUE THREAD

**Issue by PavelPolyakov** [lalalic/docx2html#1]
Hi,

Could you provide any basic example of how this could be used?
Or point me to the code line, where I can see that.

Regards,

**Comment by lalalic** [comment]
check readme

**Comment by occasl** [comment]
After using npm install to install this module and running the code similar to the README, I'm getting this:

```
Error: Cannot find module 'docx2html'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/lsacco/dev/eapps/common/doc2html/index.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

Makes no sense because I see it under node_modules in the adjacent directory to my app.js.

**Comment by ivnmaksimovic** [comment]
Same here:

```js
module.js:327
    throw err;
    ^

Error: Cannot find module 'docx2html'
    at Function.Module._resolveFilename (module.js:325:15)
```

Using `node v4.7.0` and npm `4.0.5`

**Comment by zekus** [comment]
I have the same issue as anybody else. Can you give some basic instructions on how to make this package work?

**Comment by smbat1995** [comment]
I have the same error as others

**Comment by lalalic** [comment]
please try latest version
