### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by x1911** [lalalic/docx2html#3]
it seems a very nice work, but after i install with
'npm install --save docx2html'
it throw the error

module.js:327
    throw err;
    ^

Error: Cannot find module 'docx2html'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by winstonewert** [comment]
The package.json file is improperly configured, it doesn't have a main attribute.

I found the npm package mammoth which provides the same function and actually works.
