### ISSUE TITLE
Docx from Google docs wont convert

### ISSUE THREAD

**Issue by MSevic** [lalalic/docx2html#8]
When converting docx created or edited in Google Docs or OnlyOffice nothing happens. There are no errors, it just doesn't work.

**Comment by lalalic** [comment]
emmm, never tried.

**Comment by webdagger** [comment]
Noted this too.

**Comment by SGCBB** [comment]
Can confirm, console error shows:

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'documentElement')
    at document.parse (document.js:28:3)
    at document.parse (document.js:27:3)
    at index.js:16:20`

document.js:28 points to this line `this.getPart('core-properties').documentElement`

_note:_ docx4js will load these files without error

**Comment by arpitBhalla** [comment]
> Can confirm, console error shows:
> 
> `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'documentElement') at document.parse (document.js:28:3) at document.parse (document.js:27:3) at index.js:16:20`
> 
> document.js:28 points to this line `this.getPart('core-properties').documentElement`
> 
> _note:_ docx4js will load these files without error

Getting same error

Even docx4js isn't working for me.

**Comment by matheusAle** [comment]
any update on this? @arpitBhalla  and @SGCBB
